---
# handlers file for role

- name: pull_new_images
  become: true
  docker_service:
    project_src: "{{ swt_path }}/"
    project_name: "swt-server"
    pull: yes
  listen: rebuild_containers

- name: delete_containers
  become: true
  docker_service:
    project_src: "{{ swt_path }}/"
    project_name: "swt-server"
    state: absent
    pull: yes
  listen: rebuild_containers

- name: start_containers
  become: true
  docker_service:
    project_src: "{{ swt_path }}/"
    project_name: "swt-server"
    state: present
    pull: yes
  listen: rebuild_containers